{
 "title": "Nvidia-smi",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.tagValues(bucket: \"XRRMonitoring\", tag: \"host\", predicate: (r) => r._measurement == \"nvidia-smi\")\n"
   },
   {
    "name": "gpuid",
    "query": "import \"influxdata/influxdb/v1\"\n\nv1.tagValues(bucket: \"XRRMonitoring\", tag: \"gpuid\", predicate: (r) => r._measurement == \"nvidia-smi\")\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-size: 2em;\">\n  <p>You like it? You use it? It saved you a couple of hours?</p>\n  <p>Hey 👋 <a href=\"https://www.buymeacoffee.com/xrrxrr\">You can now buy me a coffee</a>! ☕️</p>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": " GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_utilization_gpu_util\" )\n    |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> toInt()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": " Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_fb_memory_usage_free\" or r[\"_field\"] == \"gpu_fb_memory_usage_total\" or r[\"_field\"] == \"gpu_fb_memory_usage_used\")\n    |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> toInt()\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_product_architecture\" or r[\"_field\"] == \"gpu_product_brand\" or r[\"_field\"] == \"gpu_product_name\" or r[\"_field\"] == \"gpu_cuda_version\" or r[\"_field\"] == \"gpu_driver_version\")\n  |> last()\n  "
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_product_architecture\" or r[\"_field\"] == \"gpu_product_brand\" or r[\"_field\"] == \"gpu_product_name\" or r[\"_field\"] == \"gpu_cuda_version\" or r[\"_field\"] == \"gpu_driver_version\")\n  |> last()\n  "
    }
   ]
  },
  {
   "title": "ECC Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_ecc_mode_current_ecc\" )\n  |> last()\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_product_architecture\" or r[\"_field\"] == \"gpu_product_brand\" or r[\"_field\"] == \"gpu_product_name\" or r[\"_field\"] == \"gpu_cuda_version\" or r[\"_field\"] == \"gpu_driver_version\")\n  |> last()\n  "
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product_architecture\" or r[\"_field\"] == \"product_brand\" or r[\"_field\"] == \"product_name\" or r[\"_field\"] == \"driver_version\" or r[\"_field\"] == \"cuda_version\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Cuda Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product_architecture\" or r[\"_field\"] == \"product_brand\" or r[\"_field\"] == \"product_name\" or r[\"_field\"] == \"driver_version\" or r[\"_field\"] == \"cuda_version\")\n  |> last()\n"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_fb_memory_usage_free\" or r[\"_field\"] == \"gpu_fb_memory_usage_reserved\" or r[\"_field\"] == \"gpu_fb_memory_usage_total\" or r[\"_field\"] == \"gpu_fb_memory_usage_used\")\n    |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> toInt()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_utilization_encoder_util\" or r[\"_field\"] == \"gpu_utilization_gpu_util\" or r[\"_field\"] == \"gpu_utilization_memory_util\" or r[\"_field\"] == \"gpu_utilization_decoder_util\")\n    |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> toInt()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "PCI bandwith utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_pci_rx_util\" or r[\"_field\"] == \"gpu_pci_tx_util\")\n  |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> toFloat()\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Energy and Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"strings\"\nimport \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_power_readings_power_draw\" or r[\"_field\"] == \"gpu_power_readings_power_limit\" or r[\"_field\"] == \"gpu_power_readings_min_power_limit\" or r[\"_field\"] == \"gpu_power_readings_max_power_limit\")\n   |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> filter(fn: (r) => r._value != \"\")\n  |> toFloat()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\", \"_field\"], valueColumn: \"_value\")\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature / Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"regexp\"\nimport \"internal/debug\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_fan_speed\" or r[\"_field\"] == \"gpu_temperature_gpu_temp\" or r[\"_field\"] == \"gpu_temperature_memory_temp\" or r[\"_field\"] == \"gpu_temperature_gpu_temp_max_threshold\" or r[\"_field\"] == \"gpu_temperature_gpu_target_temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> filter(fn: (r) => r._value != \"\")\n  |> toInt()\n  \n  |> yield(name: \"last\")\n"
    }
   ]
  },
  { "title": "Clocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Clocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n |> filter(fn: (r) => r[\"_field\"] == \"gpu_clocks_graphics_clock\" or r[\"_field\"] == \"gpu_clocks_sm_clock\" or r[\"_field\"] == \"gpu_clocks_mem_clock\" or r[\"_field\"] == \"gpu_clocks_video_clock\")\n   |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> toInt()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_applications_clocks_setting\"   or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_display_clocks_setting\" or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_gpu_idle\" or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_hw_power_brake_slowdown\" or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_hw_slowdown\" or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_sw_thermal_slowdown\" or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_sync_boost\" or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_hw_thermal_slowdown\" or r[\"_field\"] == \"gpu_clocks_throttle_reasons_clocks_throttle_reason_sw_power_cap\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n\n        r with _value: if r._value == \"Active\" then 1 else 0\n    }))\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n|> rename(columns: {\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_applications_clocks_setting\": \"applications_clocks_setting\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_display_clocks_setting\": \"display_clocks_setting\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_gpu_idle\": \"gpu_idle\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_hw_power_brake_slowdown\": \"hw_power_brake_slowdown\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_hw_slowdown\": \"hw_slowdown\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_sw_thermal_slowdown\": \"sw_thermal_slowdown\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_sync_boost\": \"sync_boost\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_hw_thermal_slowdown\": \"hw_thermal_slowdown\",\n        \"gpu_clocks_throttle_reasons_clocks_throttle_reason_sw_power_cap\": \"sw_power_cap\"\n    })"
    }
   ]
  },
  { "title": "Encoder Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Encoder Stats",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_encoder_stats_average_fps\" or r[\"_field\"] == \"gpu_encoder_stats_average_latency\")\n  \n   |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> toFloat()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Session Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 33 },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"XRRMonitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> filter(fn: (r) => r[\"gpuid\"] == \"${gpuid}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nvidia-smi\")\n  |> filter(fn: (r) => r[\"_field\"] ==\"gpu_encoder_stats_session_count\")\n  \n   |> map(fn: (r) => ({\n      r with\n      _value: regexp.findString(v: string(v: r._value), r: /^(\\d+(?:\\.\\d+)?)/)\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> toInt()\n",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}